Add call to "GlobalNPC.PostDraw"
tModLoader/tModLoader pull request #1251
Opened 2020-12-27 01:16 UTC by Chik3r

### What is the bug?
`GlobalNPC.PostDraw` is only called when `PreDraw` returns false

### How did you fix the bug?
By adding a call to `NPCLoader.PostDraw` inside the `DrawNPCDirect` method. The call was added in the same position as it was in 1.3

### Are there alternatives to your fix?
no

Also, can whoever accepts this merge this PR and #1250 to `1.4_mergedtesting` so that I can finish making `ModdersToolkit` work for that branch.

2020-12-27 02:47 UTC, Mirsario requested changes
There seem to be a lot of returns and gotos in-between the PreDraw and that PostDraw you readded, and the location of PreDraw seems random to me. The method those are in may be better off just being split into 2 and wrapped around with PreDraw and PostDraw, like this:

![image](https://user-images.githubusercontent.com/6795251/103162848-d7a74780-4806-11eb-9ff9-67ac2c544785.png)

2020-12-27 03:20 UTC, Chicken-Bones commented
Excellent job adding patch context, but Mirsario is right, to capture PostDraw on all NPCs with all those returns you'll need to wrap the method

2020-12-27 16:13 UTC, Chik3r commented
So I did what you said, but I still left some code above the wrap, since the code for `PreDraw` uses `npcColor` which is calculated above, and I didn't want to move 50 lines of code somewhere else.
![image](https://user-images.githubusercontent.com/31808958/103174954-2e337680-4845-11eb-894a-4ba1237afad1.png)

2021-01-28 12:06 UTC, Mirsario approved these changes

2021-01-28 12:06 UTC, merged