[1.4] ModifyGlobalLoot
tModLoader/tModLoader pull request #1286
Opened 2021-01-14 20:58 UTC by kittenchilly

I forgot this in the initial bestiary PR, but there is now a separate hook in GlobalNPC that allows you to modify global loot rules (loot rules that apply to literally every npc, like souls and biome keys). Also includes a small example in ExampleNPCLoot for how to use it.

2021-01-14 21:33 UTC, Mirsario requested changes
There should be a way to enumerate and remove such drops, same as with normal NPCLoot.

2021-01-17 21:06 UTC, kittenchilly commented
> There should be a way to enumerate and remove such drops, same as with normal NPCLoot.

Vanilla doesn't have that, so I'd have to patch vanilla a bunch to get it to work that same as the normal NPCLoot. I don't think its really necessary anyways since drops are going to be conditional anyways (besides removing vanilla global loot, I guess)

2021-01-29 00:17 UTC, Mirsario commented
> 
> 
> > There should be a way to enumerate and remove such drops, same as with normal NPCLoot.
> 
> Vanilla doesn't have that, so I'd have to patch vanilla a bunch to get it to work that same as the normal NPCLoot. I don't think its really necessary anyways since most drops using this are going to be conditional. (Besides removing vanilla global loot, I guess)

I did it now with 1 patch, which changes protection of a field.

2021-01-29 00:17 UTC, Mirsario approved these changes

2021-01-29 00:26 UTC, merged