DustID
tModLoader/tModLoader pull request #1343
Opened 2021-02-27 01:10 UTC by SmugBlanco

Current state:
DustID is barebones and barely utilized due to that fact. You would often have to refer to the popular forum page 'Dust and Sound Catalogue 2' just to get a semi accurate image of what the dust may be used for.

Proposed changes:
This, a more flushed out DustID class who's variables are named after my best guess of it's original implementation purpose or most popular usage of it.

2021-02-27 12:14 UTC, Mirsario requested changes
I should've told you the following in discord right away:
- Additions should be in DustID.TML.cs partial file.
- Don't remove or rename vanilla entries.
- There's no need for line breaks, but you can have them in the partial file, outside patches.

2021-02-27 14:47 UTC, SmugBlanco commented
My bad, undid and the changes to vanilla as you said and made the changes into a partial class.

2021-02-27 22:01 UTC, direwolf420 commented on patches/tModLoader/Terraria.ID/DustID.TML.cs
> +		public const short Grass_Small = 3;
> implimentation

2021-02-28 12:17 UTC, Mirsario commented on patches/tModLoader/Terraria.ID/DustID.TML.cs
> +		public const short Grass_Small = 3;
```suggestion
	{
		//Naming is based on the best approximation of the earliest or most popular implementation.
		public const short Grass_Small = 3;
```

2021-03-07 10:37 UTC, Mirsario approved these changes
I had a complaint about underscores, but democracy happened:

2021-03-07 10:39 UTC, merged