Ported more EM
tModLoader/tModLoader pull request #1425
Opened 2021-04-04 16:40 UTC by NotLe0n

### What are the changes to ExampleMod?
- Ported ExampleHood, 
- Ported ExampleCustomAISlimeNPC (formally Flutter Slime),
- Ported ExampleTooltipsItem (formally Face)
- Ported ExampleFishingRod
- Ported ExampleSimpleMinion
- Moved MinionBossEye to new "Minions" Folder

2021-04-06 17:35 UTC, Agrair requested changes
Everything looks good to me

2021-04-07 16:03 UTC, Mirsario requested changes

2021-04-07 16:03 UTC, Mirsario commented on ExampleMod/Content/Items/Armor/ExampleBreastplate.cs
>  		}
All AddRecipes() overrides in files that don't particularly showcase anything related to recipes should require 1 ExampleItem to craft, and also this notice at the top:
```cs
// Please see Content/ExampleRecipes.cs for a detailed explanation of recipe creation.
public override void AddRecipes() {
```
There's no need for comments besides that one.

2021-04-07 16:03 UTC, Mirsario commented on ExampleMod/Content/Items/Armor/ExampleHood.cs
> +			Item.width = 18; // width of the item
Not too important, but try to keep comments in the `// Comment`  format. In other words, just add capitalization.

2021-04-07 20:28 UTC, Mirsario approved these changes

2021-04-07 20:31 UTC, merged