[1.4] Time dilation + more precise time control
tModLoader/tModLoader pull request #1602
Opened 2021-07-05 21:35 UTC by ThomasThePencil

### Overview
This PR aims to make it easier to more precisely control the flow of time, as well as finally making it possible for modders to force time, tile updates, or event updates (more on that in a second) to flow slower than normal.

### What all is done
- Added `Main.desiredWorldEventsUpdateRate`.
  - A lot of things are now tied to this instead of `Main.dayRate`, such as fallen star spawns, weather updates, and Travelling Merchant spawns.
  - By default, this is the same as `Main.dayRate`, mimicking vanilla behavior.
- All time-related fields have been made doubles with very few exceptions; the way a lot of things check for the passage of time has been adjusted to account for the new changes.
  - This means it is now possible to have `Main.dayRate` be lower than 1, causing time to flow slower than normal. The same applies for `Main.desiredWorldTilesUpdateRate` and the new `Main.desiredWorldEventsUpdateRate` field.

#### Why use doubles instead of floats?
Two reasons.
- Firstly and most importantly, this allows an incredible degree of precision when working with time, the rate at which it flows, and related fields --- which, given the integral importance of time to the flow of the game, is very important.
- Secondly and perhaps less importantly, `Main.time`, the field responsible for controlling the flow of time is a double --- it's nice to be consistent.

2021-07-17 22:19 UTC, Mirsario approved these changes

2021-07-27 02:13 UTC, Chicken-Bones requested changes

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/GameContent/Events/MysticLogFairiesEvent.cs.patch
> ++			for (int i = 1; i < (int)_timePass; i++) {
This needs to be `<=`

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/GameContent/Events/Sandstorm.cs.patch
> ++						for (int i = 1; i < (int)_timePass; i++) {
Also here

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Graphics/Effects/SkyManager.cs.patch
> ++			for (int i = 1; i < (int)_timePass; i++) {
and here

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++				if (cloudBGActive == 1f && rand.Next((int)((float)(num2 * 2 / Math.Max(desiredWorldEventsUpdateRate, 1)) * num3)) == 0) {
These int casts seem like they'll round to 0 in some cases. Should use a float based rand.Next

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++			for (int i = 1; i < (int)timePass; i++) {
`<=`

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++								else if (rand.Next((int)(num * 2)) == 0)
random and int casts

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/IO/WorldIO.cs
> +				["alteredVanillFields"] = SaveAlteredVanillaFields()
typo

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/ModLoader/IO/WorldIO.cs
> +			LoadAlteredVanillaFields(tag.GetCompound("alteredVanilla"));
key mismatch with above

2021-07-27 02:13 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/WorldGen.cs.patch
> ++			for (int l = 1; l < (int)_timePass; l++) {
`<=`

2021-07-27 04:53 UTC, Chicken-Bones requested changes

2021-07-27 04:53 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++			if (cloudBGActive == 0f && rand.NextDouble() <= 1 / ((num2 * 12 / desiredWorldEventsUpdateRate) / num3)) {
change
`1 / ((num2 * 12 / desiredWorldEventsUpdateRate) / num3)`
to
`num3 * desiredWorldEventsUpdateRate / (num2 * 12 )`

2021-07-27 04:53 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++						if (rand.NextFloat() <= 1f / num5)
This code is weird. It looks like, in vanilla, the faster the day is going, the rarer lightning gets?
Unfortunately that means if someone sets `desiredWorldEventsUpdateRate` small enough here, then you'll get lightning every frame...

2021-07-31 10:19 UTC, Chicken-Bones commented on patches/tModLoader/Terraria/Main.cs.patch
> ++						if (rand.NextFloat() <= 1f / Math.Max(num5, 2400))
I checked the surrounding code. `UpdateWeather` is called once per day 'tick' and if the day is running super slow, your other changes will ensure the calculations are correct. You should actually do `num5 *= Math.Max(desiredWorldEventsUpdateRate, 1)`

2021-08-01 02:23 UTC, merged