[1.4] Re-added extensive DustID.cs and added DustID.TML.cs
tModLoader/tModLoader pull request #1653
Opened 2021-08-01 01:22 UTC by RighteousRyan1

I re-addition of DustID extension by @SmugBlanco. Might need changes in the future, but for now, this should be good.

2021-08-01 10:04 UTC, Mirsario requested changes

2021-08-01 18:03 UTC, RighteousRyan1 commented on patches/tModLoader/Terraria/IngameOptions.cs.patch
> + 					Close();
Don't know why that's there at all

2021-08-01 18:03 UTC, RighteousRyan1 commented on patches/tModLoader/Terraria/IngameOptions.cs.patch
> + 					Close();
i already implemented SystemLoader.PreSaveAndQuit in another PR

2021-08-01 19:11 UTC, closed without merging

2021-08-01 19:11 UTC, RighteousRyan1 commented
Closed since I was mysteriously a months behind in pull requests.

2021-08-05 01:59 UTC, JavidPack commented
Isn't this fine to Squash and Merge now?